### ISSUE TITLE
snmpv3

### ISSUE THREAD

**Issue by allenmchan** [isalgueiro/otilio#2]
This looks great. 
Any plans to provide support for snmpv3?

**Comment by isalgueiro** [comment]
Thanks! Right now you should be able to connect to a v3 server with `version: 3` option in `otilio.yml`, but there's no auth support yet :/

I'll keep this issue open to track v3 support.

**Comment by isalgueiro** [comment]
Added some basic v3 support in #3 see this [v3 configuration example](https://github.com/isalgueiro/otilio/blob/master/otilio.snmpv3.yml)

For now we only support SHA auth and DES encryption, hope this also covers your use case.

I'm uploading binnary packages to 5.6.8-SNAPSHOT2 release later today.

Let me know if this fixes the issue for you.

**Comment by isalgueiro** [comment]
Got some issues with my build environment, x86_64 packages are available in release [5.6.8-SNAPSHOT2](https://github.com/isalgueiro/otilio/releases/tag/5.6.8-SNAPSHOT2)
