### ISSUE TITLE
Compatibility with 6.x

### ISSUE THREAD

**Issue by rdrgporto** [isalgueiro/otilio#4]
Hi!

I would like to know if there is some possibility to integrate **Otilio** on **6.x**. For instance, if one wants to send data to **Logstash**, index creation on **6.x** is different from **5.x**:

**6.x**
```javascript
output {
 elasticsearch {
  hosts => "localhost:9200"
  manage_template => false
  index => "%{\[@metadata\]\[beat\]}-%{\[@metadata\]\[version\]}-%{+YYYY.MM.dd}"
  document_type => "%{\[@metadata\]\[type\]}"
 }
}
```
**5.x**
```javascript
output {
 elasticsearch {
  hosts =>  "localhost:9200"
  manage_template =>  false
  index =>  "%{\[@metadata\]\[beat\]}-%{+YYYY.MM.dd}"
  document_type =>  "%{\[@metadata\]\[type\]}"
  }
}
```
Thanks in advance,

Regards 🖖

**Comment by isalgueiro** [comment]
Sup :fist_oncoming: 

Thanks for documenting this! Otilio is built with libbeat 5.6, so field `[@metadata][version]` [is not available](https://www.elastic.co/guide/en/beats/filebeat/5.6/logstash-output.html#_accessing_metadata_fields), as this field [was added in branch 6](https://www.elastic.co/guide/en/beats/filebeat/6.2/logstash-output.html#_accessing_metadata_fields). 

As a workaround you can use `beat.version` source field
```
2018/03/07 10:20:00.882680 client.go:214: DBG  Publish: {
  "@timestamp": "2018-03-07T10:20:00.882Z",
  "beat": {
    "hostname": "ubuntu",
    "name": "ubuntu",
    "version": "5.6.8-3"
  },
  "snmp.host": "127.0.0.1",
  "sysDescr": "Linux ubuntu 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64",
  "sysUpTime": "179462",
  "type": "otilio"
}
```
I'll update this issue If we end up updating libbeat to 6.x branch.
