### ISSUE TITLE
`go get github.com/isalgueiro/otilio` fails

### ISSUE THREAD

**Issue by sakurai-youhei** [isalgueiro/otilio#5]
`go get` fails as below. What's wrong?

```
$ docker run -it golang go get github.com/isalgueiro/otilio
# cd /go/src/github.com/isalgueiro/otilio; git submodule update --init --recursive
fatal: No url found for submodule path 'src/github.com/MichaelTJones/walk' in .gitmodules
package github.com/isalgueiro/otilio: exit status 128
```

Thank you.

**Comment by sakurai-youhei** [comment]
Could https://github.com/sakurai-youhei/otilio/commit/228bbac3481224e3e9036b94dfc59f5225211779 be a fix? Because I'm quite newbie in golang (and git), I'm not enough sure to open PR with it. Thank you.

**Comment by isalgueiro** [comment]
Clone the project in `${GOPATH}/github.com/isalgueiro/otilio`. Check out [Elastic beats developer guide](https://www.elastic.co/guide/en/beats/devguide/6.1/new-beat.html).

**Comment by sakurai-youhei** [comment]
Thank you. Anyways, it is ok for me now as I managed `go get` by https://github.com/sakurai-youhei/otilio/commit/1f9ec3182fa66bba39d5ea131469d251a45855c4 in [sakurai-youhei/otilio](https://github.com/sakurai-youhei/otilio).

```
$ docker run -it golang go get github.com/sakurai-youhei/otilio
```

FYI: Any Go apps that I have played can be built by `go get` like these. That's why I thought `go get`  should be supported by all of Go apps including yours.

```
$ docker run -it golang go get github.com/golang/example/hello
$ docker run -it golang go get github.com/hartfordfive/protologbeat
$ docker run -it golang go get github.com/elastic/beats/heartbeat
$ docker run -it golang go get github.com/elastic/beats/metricbea
```
